"""Headless execution / drift guard for the Tier-B replication notebooks.

Part of the P1 "Tier B replication notebooks" campaign (see
``.tierd_campaign/CAMPAIGN.md``). Each notebook in
``Paper-JSS/replication/notebooks/`` ends with a drift-guard cell that asserts
the estimator reproduces the paper's pinned headline number on the bundled real
data. Executing the notebook therefore *is* the regression test: if `sp.synth`,
`sp.rdrobust`, `sp.ivreg`, `sp.regress`, or `sp.match` drifts away from the
pinned value, the assertion raises and this test fails.

Requires the ``notebooks`` extra (``pip install -e ".[notebooks]"``); the test
skips cleanly when the headless-execution stack is unavailable so the default
suite still runs for users who have not installed it.

Notebooks are regenerated by ``scripts/build_replication_notebooks.py``; this
test is deliberately decoupled from that generator (it runs whatever .ipynb
files are checked in, so a hand-edit that breaks reproduction is also caught).
"""

import glob
import os

import pytest

nbformat = pytest.importorskip("nbformat", reason="notebooks extra not installed")
nbclient = pytest.importorskip("nbclient", reason="notebooks extra not installed")
pytest.importorskip("ipykernel", reason="notebooks extra not installed")

from nbclient.exceptions import CellExecutionError  # noqa: E402

_NB_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "Paper-JSS",
    "replication",
    "notebooks",
)
_NOTEBOOKS = sorted(glob.glob(os.path.join(_NB_DIR, "*.ipynb")))

# The Tier-B notebooks live under ``Paper-JSS/`` — a *separate private repo*
# that the public main repo gitignores (CLAUDE.md §9.1). A clean public-only
# checkout therefore has no notebooks; skip rather than fail there. When the
# combined tree (maintainer / JSS archive) is present, run the full guard.
if not _NOTEBOOKS:
    pytest.skip(
        "Paper-JSS replication notebooks not present in this checkout "
        "(they live in the private Paper-JSS repo)",
        allow_module_level=True,
    )


@pytest.mark.parametrize(
    "nb_path", _NOTEBOOKS, ids=[os.path.basename(p) for p in _NOTEBOOKS]
)
def test_replication_notebook_executes_and_reproduces(nb_path):
    """Run the notebook end-to-end; any cell error (incl. a drift-guard
    ``assert``) fails the test."""
    nb = nbformat.read(nb_path, as_version=4)
    client = nbclient.NotebookClient(
        nb,
        timeout=600,
        kernel_name="python3",
        resources={"metadata": {"path": _NB_DIR}},
    )
    try:
        client.execute()
    except CellExecutionError as exc:  # pragma: no cover - failure path
        pytest.fail(
            f"{os.path.basename(nb_path)} failed to reproduce its pinned "
            f"numbers (drift guard or execution error):\n{exc}"
        )
